Modified the rollback mechanism

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -46,7 +46,7 @@ steps:
   - | 
       if [ -d "environments/$BRANCH_NAME/" ]; then
         cd environments/$BRANCH_NAME
-        terraform plan
+        terraform plan -var="build_id=$_BUILD_ID" || echo "fail" > /workspace/fail.flag
       else
         for dir in environments/*/
         do 
@@ -57,7 +57,7 @@ steps:
           echo "*************** TERRAFORM PLAN ******************"
           echo "******* At environment: ${env} ********"
           echo "*************************************************"
-          terraform plan || exit 1
+          terraform plan -var="build_id=$_BUILD_ID" || { echo "fail" > /workspace/fail.flag; exit 1 }
           cd ../../
         done
       fi 
@@ -71,7 +71,7 @@ steps:
   - | 
       if [ -d "environments/$BRANCH_NAME/" ]; then
         cd environments/$BRANCH_NAME      
-        terraform apply -var="build_id="$_BUILD_ID" -auto-approve
+        terraform apply -var="build_id="$_BUILD_ID" -auto-approve || echo "fail" > /workspace/fail.flag
       else
         echo "***************************** SKIPPING APPLYING *******************************"
         echo "Branch '$BRANCH_NAME' does not represent an official environment."
@@ -85,10 +85,13 @@ steps:
   args:
     - '-c'
     - |
-        if [ "$BUILD_STATUS" != "SUCCESS" ]; then
+        if [ -f /workspace/fail.flag ]; then
+          echo "Detected build failure — rolling back this build's resources..."
           cd environments/$BRANCH_NAME
           terraform init
-          terraform destroy -var="build_id=$_BUILD_ID" -auto-approve
+          terraform destroy -var="build_id=$_BUILD_ID" -auto-approve || echo "Rollback failed."
+        else
+          echo "Build succeeded — skipping rollback."
         fi
   waitFor: ['-']
 
