misplaced quotation mark

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -71,7 +71,7 @@ steps:
   - | 
       if [ -d "environments/$BRANCH_NAME/" ]; then
         cd environments/$BRANCH_NAME      
-        terraform apply -var="build_id="$_BUILD_ID" -auto-approve || echo "fail" > /workspace/fail.flag
+        terraform apply -var="build_id=$_BUILD_ID" -auto-approve || echo "fail" > /workspace/fail.flag
       else
         echo "***************************** SKIPPING APPLYING *******************************"
         echo "Branch '$BRANCH_NAME' does not represent an official environment."
